import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-br from-zinc-950 via-zinc-900 to-zinc-800 min-h-screen text-white`}
      >
        <div className="w-screen mx-auto p-12">
          <div className="rounded-2xl shadow-2xl border border-zinc-800 bg-zinc-900/80 backdrop-blur">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
